services:

  app:
    build: .
    command: |
      sh -c "
        npm run start --tunnel
      "
    env_file:
      - .env
    tty: true
    ports:
      - 8081:8081
    stdin_open: true
    volumes:
      - ./assets:/app/assets
      - ./App.js:/app/App.js
      - ./app.json:/app/app.json
      - ./babel.config.js:/app/babel.config.js
